targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: false
          generate_connect_constructor: true
      
      freezed:
        options:
          map_props: true
          from_json: true
          to_json: true
          equal: true
          copy_with: true
      
      json_serializable:
        options:
          any_map: true
          checked: true
          explicit_to_json: true
          field_rename: snake
          include_if_null: false